name: Build and deploy Flask app to Azure Web App - ChatBot-PDF-backend

on:
  push:
    branches:
      - backend  # Trigger on pushes to the backend branch
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Changed to a Linux runner as it's more common for Python

    steps:
    - uses: actions/checkout@v4  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Ensure this matches the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_431988983063410782CF87E38DFC6F5A }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1538EDD5012F42DE9F2C38D4385D22F9 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_24799376E9074E27A93A16023A4BD4DB }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ChatBot-PDF-backend'  # Make sure this matches the name of your Azure Web App
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

    - name: Post deployment action
      run: echo "Deployed successfully to Azure Web App!"

