# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - ChatBot-PDF

on:
  push:
    branches:
      - backend
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Specify your Node.js version
    - name: Install dependencies
      run: npm install
      working-directory: ./Client
    - name: Build React app
      run: CI=false npm run build
      working-directory: ./Client
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v2
      with:
        name: react-build
        path: ./Client/build
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    #   working-directory: ./Server
    # - name: Prepare backend for deployment
    #   run: |
    #     zip -r backend.zip .
    #   working-directory: ./Server

    # - name: Upload backend artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #       name: flask-backend
    #       path: ./Server/backend.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:


      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A80C320DCF9F4A709E26B1C12E871E31 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5CEB2698E8BA413F8F69725106B2BAC7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5EFF3E169D0042CBACFD4F13B1615521 }}
      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: react-build
      # - name: Download backend artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: flask-backend
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ChatBot-PDF'
          slot-name: 'Production'
          package: .
      - name: Output Web App URL
        run: echo "Flask app running on ${{ steps.deploy-to-webapp.outputs.webapp-url }}"

          
